apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudpulse.fullname" . }}-config
  labels:
    {{- include "cloudpulse.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}